import type { Feature as F, Geometry, GeoJsonProperties, BBox } from 'geojson';
export type Link = {
  href: string;
  rel: string;
  title?: string;
  hreflang?: string;
  length?: string;
  templated?: boolean;
  type?: string;
  channel?: string;
};

export type LandingPage = {
  links: Link[];
  title?: string;
  description?: string;
};

export interface Collection extends LandingPage {
  id: string;
  storageCrsCoordinateEpoch?: number;
  crs: Array<string>;
  storageCrs?: string;
  itemType?: string | 'feature';
  extent: Extent;
}

export type Interval = [string | null, null | string];
export interface Extent {
  spatial: {
    bbox: BBox[];
    crs: string;
  };
  temporal: {
    interval: Array<Interval>;
    trs: string;
  };
}

export interface Feature<
  G extends Geometry = Geometry,
  P extends GeoJsonProperties = GeoJsonProperties,
> extends F<G, P> {
  id: string | number;
  links?: Link[];
}

export interface ConformancePage {
  links?: Link[];
  conformsTo: string[];
}

export type FeatureCollection<
  G extends Geometry = Geometry,
  P extends GeoJsonProperties = GeoJsonProperties,
> = {
  type: 'FeatureCollection';
  features: Feature<G, P>[];
  /**
   * Automatically generated by the response handler
   */
  timeStamp?: string;
  /**
   * Automatically generated by the response handler
   */
  numberMatched?: number;
  /**
   * Automatically generated by the response handler
   */
  numberReturned?: number;
  links?: Link[];
};
